# Generated by Django 2.1.5 on 2019-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
