"""Added Column ModifiedDate"

Revision ID: 11e70efa4b3d
Revises: 1b5787a30fab
Create Date: 2019-01-06 13:34:42.894361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e70efa4b3d'
down_revision = '1b5787a30fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ModifiedDate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ModifiedDate')
    # ### end Alembic commands ###
