"""Post Changes

Revision ID: 1b5787a30fab
Revises: 367df931dec6
Create Date: 2019-01-06 01:30:49.247767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5787a30fab'
down_revision = '367df931dec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Text(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CreatedDate', sa.Text(), nullable=True),
    sa.Column('CreatorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CreatorId'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
