"""Basic Schema Created

Revision ID: 367df931dec6
Revises: 
Create Date: 2019-01-05 15:30:09.954826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367df931dec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.Text(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=True),
    sa.Column('PasswordHash', sa.Text(), nullable=True),
    sa.Column('ProfilePic', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
