"""Login Created

Revision ID: c02b7517df97
Revises: 
Create Date: 2019-01-01 22:16:15.502745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02b7517df97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=64), nullable=True),
    sa.Column('Username', sa.String(length=64), nullable=True),
    sa.Column('PasswordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_index(op.f('ix_Users_Username'), 'Users', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_Username'), table_name='Users')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
