"""empty message

Revision ID: 83ee6dd45a48
Revises: 
Create Date: 2019-01-01 19:46:56.852957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ee6dd45a48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppyId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppyId'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('toys',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppyId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppyId'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    op.drop_table('owner')
    op.drop_table('puppies')
    # ### end Alembic commands ###
