"""Added New Column age

Revision ID: e60d207e7050
Revises: 27bc386d4324
Create Date: 2019-01-01 14:53:42.310440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60d207e7050'
down_revision = '27bc386d4324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'age')
    # ### end Alembic commands ###
